### ISSUE TITLE
request url is broken on 1.8.1

### ISSUE THREAD

**Issue by sohobloo** [ZacharyL2/electron-request#7]
request('http://a.b/c?d=e') will produce a mistake url option to `electronAdapter` like: 
http://a.b/c?d=e/c?d=e

https://github.com/islizeqiang/electron-request/compare/v1.8.0...v1.8.1#diff-7233c116d620a52e91b99f0e3808c4b546e99490f5cdc9d7dda82b6a585b1c34L43

**Comment by ZacharyL2** [comment]
Fixed in 1.8.2
