### ISSUE TITLE
Pathname is duplicated when sending request

### ISSUE THREAD

**Issue by pgenfer** [ZacharyL2/electron-request#8]
Hi,
When sending a request with an URL that contains an additional path name, e.g.
   > https://my-domain.com/path
   
The resulting URL in the request ends up being:
   > https://my-domain.com/path/path

I guess this behavior was introduced with the latest change in file [RequestClient.ts L44](https://github.com/islizeqiang/electron-request/blob/master/src/Request/ElectronRequestClient.ts#L44):
```typescript
 url: `${requestURL}${pathname}${search || ''}`,
``` 
The URL for the final request is constructed from the incoming URL (which already contains the path) and the pathname extracted by the URL class, resulting in a duplicate path - or am I missing something here?

If you like, I could also try to create a pull request with the fix.

Thank you and best regards,
Patric

**Comment by ZacharyL2** [comment]
Thanks, Patric, I've tried to fix it in 1.8.2, you can reinstall it to verify.

**Comment by pgenfer** [comment]
Hi @ZacharyL2 ,
I just tried 1.8.2 and can confirm that it works, thanks a lot!
Closing this issue as it's fixed now.
Thanks again and best regards,
Patric
